### ISSUE TITLE
Could not save object in repository., Cause: javax.jcr.nodetype.ConstraintViolationException: NT6577E: The value for the binary property ibmcontentwcm:html on node /contentRoot/icm:libraries[15]/Content/script portlet applications/angular 8 cli contacts sample/ibmcontentwcm:elements[15] exceeds its max length.  The max length is 2000000 while the value is of length 2001613

### ISSUE THREAD

**Issue by meghnapradhanhcl** [HCL-TECH-SOFTWARE/sample-angular-script-application#16]
From where can I configure this value?
ScriptPortletServer = http://127.0.0.1:30015

I want to deploy this on my local DX server 
http://localhost:10039/wps/portal/

Below is the log file after running sp push command below from the dist/ folder:
sp push -wcmContentName "Angular 8 CLI Contacts Sample"

2021-05-28 12:51:26 -- Script Application command line utility version: 8.5

2021-05-28 12:51:26 -- Script Application command line utility build number: 20200708-1300

2021-05-28 12:51:26 -- Home folder: /Users/meghnapradhan/Documents/DXSoftware/digexp-toolkit-2.0.0/digexp-sp-cmd

2021-05-28 12:51:26 -- NodeJS environment:

	spConfig = /Users/meghnapradhan/Documents/DXSoftware/digexp-toolkit-2.0.0/digexp-sp-cmd/sp-config.json
	nodePath = /usr/local/bin/node
	version  = v14.17.0

2021-05-28 12:51:26 -- Effective configuration properties: 

	scriptPortletServer = http://127.0.0.1:30015
	laxSSL = false
	performAuth = true
	portalUser = wpsadmin
	portalPassword = ********
	wcmSiteArea = Script Application Library/Script Applications/
	excludes = [^bin$, ^lib$, ^src$, ^node_modules$, ^\.classpath$, ^\.project$, ^\..*ignore$, ^sp-config.json$, ^sp-cmdln.log$, ^sp.bat$, ^sp.sh$]
	wcmContentName = Angular 8 CLI Contacts Sample
	contentRoot = /Users/meghnapradhan/Documents/ScriptApplications/sample-angular-script-application-master/dist

2021-05-28 12:51:26 -- Begin content push to Portal.

2021-05-28 12:51:26 -- Accept-Language: en-IN,en

2021-05-28 12:51:29 -- EJPRC0028E: Application push failed with one or more errors.

RequestError: connect ECONNREFUSED 127.0.0.1:30015
    at ClientRequest.<anonymous> (/Users/meghnapradhan/Documents/DXSoftware/digexp-toolkit-2.0.0/node_modules/got/dist/source/core/index.js:841:25)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:388:22)
    at ClientRequest.origin.emit (/Users/meghnapradhan/Documents/DXSoftware/digexp-toolkit-2.0.0/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Comment by sihunqu123** [comment]
Mine error is `{  "results":{ "status":"error", "message":"EJPRD0206E: Illegal character [0x001b] found at offset [0x430fa] in file [main.26ace9a25d1180f78e8c.js]."} }`

**Comment by meghnapradhanhcl** [comment]
My issue was that the script application being deployed was of size >2MB. The issue was fixed when the build was compressed.
